(define (sum term a next b)
  (if (> a b)
    0
    (+ (term a)
       (sum term (next a) next b)
       )
    )
  )

(define (cube x)
  (* x x x)
  )

(define (even? x)
  ( = (remainder x 2) 0)
  )

(define (integral f a b n)
  (let ((index -1)
        (h (/ (- b a) n))
        )
    (define (next a)
      ( + a h)
      )
    (define (term a)
      (set! index (+ index 1))
      ;(display index) (newline)
      (if (even? index)
        (* 4 (f a))
        (* 2 (f a))
        )
      )
    (* (/ h 3)
       (+ (sum term a next b) (f b))
     )
    )
  )

(integral cube 0.0 1.0 1000)
